name:                ebmc
version:             0.1.0.0
synopsis:            Simple project template from stack
description:         Please see README.md
homepage:            https://github.com/genos/ebmc#readme
license:             BSD3
author:              Graham Enos
maintainer:          graham@quantifind.com
copyright:           Quantifind
category:            Math

ghc-options: -Wall -O2

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - lens
  - safe
  - scalpel-core
  - text
  - wreq

executables:
  ebmc:
    source-dirs:      src
    main:             Main.hs
