name:                mrs
version:             0.1.0.0
synopsis:            Monadic Recursion Schemes
description:         http://jtobin.ca/monadic-recursion-schemes
homepage:            http://jtobin.ca/monadic-recursion-schemes
license:             MIT
author:              Graham Enos
maintainer:          graham@quantifind.com
copyright:           Quantifind
category:            Math

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - containers
  - recursion-schemes
  - text
  - transformers

executables:
  mrs:
    source-dirs: src
    main: Main.hs
