name:                validation-example
version:             0.1.0.0
synopsis:            https://github.com/pittsburgh-haskell/data-validation-demo-haskell
description:         Data validation with the `validation` package
homepage:            https://github.com/pittsburgh-haskell/data-validation-demo-haskell
license:             BSD3
author:              Franklin Chen, Graham Enos
maintainer:          graham.enos@gmail.com
copyright:           Graham Enos
category:            Math

dependencies:
  - base >= 4.7 && < 5
  - validation

library:
  source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Main.hs
    dependencies:
      - hspec
      - validation-example
