name:                min-stack
license:             MIT
author:              Graham Enos
maintainer:          graham.enos@gmail.com
copyright:           2020 Graham Enos

ghc-options: -Wall -O2

dependencies:
  - base ^>= 4.12

library:
  source-dirs: lib

tests:
  min-stack-test:
    source-dirs: test
    main:        Main.hs
    dependencies:
      - min-stack
      - hedgehog ^>= 1.0.1
